version: "3.8"

services:
  db:
    container_name: trpc_test
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_trpc_test:/var/lib/postgresql/data
volumes:
  db_trpc_test:
